replicaCount: 1

image:
  repository: andreiduvakin/lectio-web
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    memory: 128Mi
    cpu: 200m

ingress:
  secretTLSName: lectio-web-tls-secret

  domain: lectio.numerum.team

  path: /
  pathType: Prefix
