apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: lectio-api-secret
                  key: SECRET_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lectio-api-secret
                  key: DB_PASSWORD
            - name: DB_DRIVER
              value: "{{ .Values.env.DB_DRIVER }}"
            - name: DB_HOST
              value: "{{ .Values.env.DB_HOST }}"
            - name: DB_PORT
              value: "{{ .Values.env.DB_PORT }}"
            - name: DB_USER
              value: "{{ .Values.env.DB_USER }}"
            - name: DB_NAME
              value: "{{ .Values.env.DB_NAME }}"
            - name: DB_SCHEMA
              value: "{{ .Values.env.DB_SCHEMA }}"
          volumeMounts:
            - name: uploads-volume
              mountPath: {{ .Values.persistence.uploads.containerPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-uploads-pvc"